services:
  db:
    build:
        context: ./schemas
        #dockerfile: Database.Dockerfile
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_USER: 'hfh'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'


    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
        context: ./Frontend 
        #dockerfile: Frontend.Dockerfile
    ports:
      - "3006:3006"
    environment:
      BACKEND_HOST: backend
    env_file:
      - .env
  
  redis:
    image: redis:6-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env
  backend:
    build:
        context: ./Backend 
        #dockerfile: Backend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      REDIS_HOST: redis
      DB_HOST: db
    env_file:
      - .env

volumes:
    backend_data:
    db_data:

version: "3.0"
